GET http://localhost:1313/users
Content-Type: application/json

###

POST http://localhost:1313/users
Content-Type: application/json

{
  "email": "Gabrielcn6@cmail.com",
  "password": "password",
  "name": "Gabriel",
  "surname": "Corvalan",
  "workIncome": 10506050,
  "otherIncome": {}
}

###
GET http://localhost:1313/users/657fb3a94471811da5dff12e/cards
Content-Type: application/json

###

POST http://localhost:1313/users/6580cc63f99c23c68644faf5/cards
Content-Type: application/json

{
  "description": "American Express",
  "bank": "Banco Macro"
}